# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iCovid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iCovid

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'lottie-ios'
pod 'Charts'
pod 'ReachabilitySwift'
pod 'CLTypingLabel'

end
